spring: 
  profiles:
    active: dev
    
---
 
spring: 
  refreshValue: wangjian
  profiles: dev
  application: 
    name: complement-config-client

server: 
  port: 9001
  
---
spring: 
  refreshValue: wangjian112
  profiles: prod
  application:
    name: complement-config-client
    
server: 
  port: 9002